version: 2
project_name: task-plus

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/task-plus
    binary: task-plus
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
