version: 2
project_name: task-plus

before:
  hooks:
    - go mod tidy

builds:
  - id: task-plus
    main: ./cmd/task-plus
    binary: task-plus
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
  - id: tp
    main: ./cmd/task-plus
    binary: tp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    builds:
      - task-plus
      - tp

release:
  github:
    owner: drummonds
    name: task-plus

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
