version: "3"

tasks:
  fmt:
    cmds:
      - go fmt ./...

  vet:
    cmds:
      - go vet ./...

  test:
    cmds:
      - go test ./...

  check:
    cmds:
      - task: fmt
      - task: vet
      - task: test

  build:
    cmds:
      - go build -o bin/task-plus ./cmd/task-plus

  deps:tidy:
    cmds:
      - go mod tidy

  clean:
    cmds:
      - rm -rf bin/ dist/
